### ISSUE TITLE
http2: tests for trailers

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#101]
As titled, we need a bunch of tests (and probably bug fix) for trailers. Who wants to add those?

This method is not covered: https://github.com/nodejs/http2/blob/master/lib/internal/http2/compat.js#L316

**Comment by marcoalbarelli** [comment]
Hi
This may be the perfect entry point for my first contribution.
How urgent  do you think this task is?
Trailers are not very much used so my gut feeling is: not that much, but of  course I may be wrong

**Comment by mcollina** [comment]
@sebdeckers why the sad face?

@marcoalbarelli I think it's a right chunk of a task :). Go ahead and write it. We would need this in some weeks, there should be plenty of time.

**Comment by sebdeckers** [comment]
@mcollina I felt guilty for skipping the trailers implementation in PR #47. 😥

**Comment by mcollina** [comment]
@sebdeckers no need, you are doing amazing work. I found out because there was a bug there, and all the tests were passing.

**Comment by marcoalbarelli** [comment]
It's taking me ages to solve this ticket I know
too bad paid work has a higher priority :\ 

If there's still time I'd _really_ like to close it, but if we don't and somebody wants to step in I'd understand

**Comment by mcollina** [comment]
keep working on it! :)

**Comment by jasnell** [comment]
@marcoalbarelli ... no worries!
