### ISSUE TITLE
missing unit tests

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#11]
I think we should track down all the part of the APIs and tests that needs to be added.
Having a list of unit tests that we want to cover makes easier for others to contribute.

**Comment by jasnell** [comment]
Agreed. It's been a bit difficult because the APIs have been a bit in flux but things should be stabilizing a bit now. Coming up with a list of possible tests should be feasible.

**Comment by mcollina** [comment]
Closing in favor of #42
