### ISSUE TITLE
http2: cookies

### ISSUE THREAD

**Issue by sebdeckers** [nodejs/http2#114]
The `set-cookie` header may appear multiple times. Its values should be handled as an Array in all response header methods.

**Comment by jasnell** [comment]
heh... great minds think alike... https://github.com/nodejs/http2/pull/115
I was just working on this :-)

**Comment by jasnell** [comment]
well... same area. at least :-) .. the mapToHeaders function was not handling multi-valued headers appropriately. This should fix that.

**Comment by sebdeckers** [comment]
@jasnell Hah, awesome!

If the HTTP/2 API supports duplicate headers for any header, the compatibility layer may need to mimic the old behaviour described in [`message.headers`](https://nodejs.org/api/http.html#http_message_headers):

> Duplicates in raw headers are handled in the following ways, depending on the header name:
> - Duplicates of age, authorization, content-length, content-type, etag, expires, from, host, if-modified-since, if-unmodified-since, last-modified, location, max-forwards, proxy-authorization, referer, retry-after, or user-agent are discarded.
> - set-cookie is always an array. Duplicates are added to the array.
> - For all other headers, the values are joined together with ', '.

**Comment by jasnell** [comment]
yeah, for the first point, we may need to enforce that at a lower level... not just in the compat layer.

**Comment by sebdeckers** [comment]
Fixed in #115 (related: #129)
