### ISSUE TITLE
http2: starting HTTP/2 with TLS ALPN

### ISSUE THREAD

**Issue by jasnell** [nodejs/http2#122]
For anyone who may want to take this one on... 

----
[Starting HTTP/2 for "https" URIs](https://tools.ietf.org/html/rfc7540#section-3.3)

> A client that makes a request to an "https" URI uses TLS [TLS12] with the application-layer protocol negotiation (ALPN) extension [TLS-ALPN].

> HTTP/2 over TLS uses the "h2" protocol identifier.  The "h2c" protocol identifier MUST NOT be sent by a client or selected by a server; the "h2c" protocol identifier describes a protocol that does not use TLS.

> Once TLS negotiation is complete, both the client and the server MUST send a connection preface (Section 3.5).
----

Using the TLS ALPN mechanism, a server can theoretically be written to listen for both HTTP/1 and HTTP/2 requests, allowing the client to determine which to use based on the protocol identified via ALPN. To support this, a new TLSServer implementation would need to be created that selects either HTTP/1 or HTTP/2 based on the ALPN value. Since HTTP/1 and HTTP/2 will be two separate code paths, requiring different handlers, this could be a bit tricky to implement.

**Comment by sebdeckers** [comment]
Happy to take a stab at this today. Will open a PR once it's working.

**Comment by sebdeckers** [comment]
Can be closed
