### ISSUE TITLE
http2: client should be unref() by default

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#140]

**Comment by c0b** [comment]
agree; i'm writing some code running as http2 client, with current node-v8.7.0 it requires me to call `client.destroy()` to quit when no other things hold the event loop

vs. http.get( ... ) does not need to worry close the connection.

**Comment by apapirovski** [comment]
@c0b I think that's a slightly different issue though because `get` is one request vs `connect` which is a whole connection. How does `net.connect` behave in a similar situation? Also it's better to open issues in the main Node tracker now that http2 is a part of core.

**Comment by jasnell** [comment]
Yep, I should actually close out all of the issues here.

The point still stands tho... we should see if there's some reasonable approach we can take here.

**Comment by apapirovski** [comment]
@jasnell I would say this is a broader issue of the client not matching the http client but in terms of how `http2.connect` works, this seems right to me since it mimics other places where a persistent connection is established (`net.connect` or `tls.connect`).

**Comment by addaleax** [comment]
Fun fact, I was actually working on a fix for this this an hour ago or so. I should have something up today or tomorrow :)

**Comment by c0b** [comment]
> Also it's better to open issues in the main Node tracker now that http2 is a part of core.

or close the whole repo instead? or just close the issues board, leave the remaining at read-only mode for another period before eventually delete
