### ISSUE TITLE
H2 Frames API

### ISSUE THREAD

**Issue by sebdeckers** [nodejs/http2#146]
* **Version**: n/a
* **Platform**: all
* **Subsystem**: http2

There are some interesting proposed HTTP extensions that define new HTTP/2 frames. For example [CACHE_DIGEST](http://httpwg.org/http-extensions/cache-digest.html#iana-considerations), [ALTSVC](http://httpwg.org/http-extensions/draft-ietf-httpbis-alt-svc.html#alt-svc-frame-registration), and [ORIGIN](http://httpwg.org/http-extensions/origin-frame.html#iana-considerations).

Just like HTTP/1 headers are extensible, I would like an API to manage custom frames in the application layer. We currently ignore unrecognised frames emitted by Nghttp2 but could bubble them up to the session.

**Comment by jasnell** [comment]
This is something that I definitely want to get through. As much as possible, for known extension frames, I would rather the support be handled at the native layer. If we want to support arbitrary extensions it should be fairly straightforward. I think we should definitely hold off a bit on this part tho and do it in a phase 2 after we land the primary support

**Comment by evert** [comment]
Is it time to reconsider this? I'd love to try my hand at a prototype cache-digest impementation

**Comment by sebdeckers** [comment]
(@evert Might be better to have this discussion at nodejs/node instead of this archived repo. The current http2 collaborators might not see this thread.)

👍🏻 I am also keen to help with a Cache Digest implementation. Exposing a custom frames API to userland JS would be fun for tinkering, but unlikely to achieve great performance. I would rather implement cache digest support in core, similar to the altsvc support. There are several fast C++ cuckoo filter implementations including a reference of the current cache digest draft spec.

For reference:

- https://github.com/yoavweiss/cache-digests-cuckoo
- https://github.com/mcollina/cuckoofilter
- https://nghttp2.org/documentation/programmers-guide.html#implement-user-defined-http-2-non-critical-extensions

**Comment by jasnell** [comment]
If cache digest reaches rfc status, then nghttp2 is likely to implement it directly. Either way, that's actually where I'd start tho.

**Comment by sebdeckers** [comment]
Relevant: https://github.com/nghttp2/nghttp2/issues/587
