### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by sebdeckers** [nodejs/http2#160]
FWIW, the author of nghttp2 just published an effort to implement QUIC called ngtcp2 at: https://github.com/ngtcp2/ngtcp2

Since we already have backwards compatibility, maybe forwards compatibility could be considered at some point. 😁

**Comment by jasnell** [comment]
QUIC support is likely going to be quite a ways out but certainly worth discussing.

**Comment by mcollina** [comment]
While I see value for the ecosystem to have http2 in core (as we have http), I see _less_ value in bringing quic in, as it is way less popular. I will try to solve the problem on how to build against Node openssl instead.

**Comment by sebdeckers** [comment]
@mcollina Agreed, still too early for sure. Adoption could increase once the QUIC specs are finalised. The QUIC-to-HTTP mapping is now being developed as a separate spec. But QUIC has very similar concepts as HTTP/2: sessions, streams, frames, options, etc. With some decoupling/abstraction (e.g. TCP socket, native bindings) it may be possible to reuse much of the JavaScript code of the HTTP/2 implementation.
