### ISSUE TITLE
Error in socketOnTimeout

### ISSUE THREAD

**Issue by sebdeckers** [nodejs/http2#179]
* **Version**: 9.0.0pre 1eec6da17d534d504ff9556912636b0ffd4326a0
* **Platform**: macOS
* **Subsystem**: http2

I'm getting some real-world traffic on my server and it occasionally throws these uncaught errors. Seems to be related to the socket timeout.

```
internal/http2/core.js:1992
    this[kSession].shutdown(
                  ^

TypeError: Cannot read property 'shutdown' of undefined
    at TLSSocket.socketOnTimeout (internal/http2/core.js:1992:19)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:402:8)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Comment by jasnell** [comment]
Looks like destroy is happening before the timeout, we need to make sure that destroying clears the timeout to avoid the issue here.

**Comment by jasnell** [comment]
Think I have this one and in the process fixed another issue.

**Comment by sebdeckers** [comment]
Great, I'll give it a try! Will reopen if I find any issues. Thanks for this.

Been meaning to write that compat documentation but haven't had much time this week because we bought a new place. Learning a lot about plastering walls though. 🤷‍♂️
