### ISSUE TITLE
http2 client: fallback to HTTP/1.1 ?

### ISSUE THREAD

**Issue by c0b** [nodejs/http2#189]
I see #125 is about to fallback to HTTP/1.1 on a http2 server side, but how about http2 client? for all current available http client connection packages on npm, I'm not seeing one support http2 yet, include the https://www.npmjs.com/package/request ; wonder is there a way to connect an api server prefer http2 but can fallback to http1 if no h2 support from the server?

can we have an option `{ allowHTTP1: true }` on `http2.connect(authority[, options][, listener])`

https://nodejs.org/api/http2.html#http2_http2_connect_authority_options_listener

**Comment by apapirovski** [comment]
Closing stale issues on this repo as the work is happening in https://github.com/nodejs/node now.
