### ISSUE TITLE
Internal buffering of writes before telling nghttp to resume a stream

### ISSUE THREAD

**Issue by jasnell** [nodejs/http2#19]

**Comment by mcollina** [comment]
it this fixed?

**Comment by kjin** [comment]
@jasnell Could you elaborate on what this means? I think I am running into something just like this -- will document in another issue.

**Comment by jasnell** [comment]
writes to a stream are buffered in a link list in the native code, and are only written out to the socket on each tick of the even loop. nghttp is prompted to write whatever data it needs. The callback will pull queued data off the linked list to send it. If there is no data for nghttp to send for a particular stream, that stream is "paused" in nghttp's internal state tracking. This issue was a todo to make sure that the stream was unpaused when there was actually new data queued up for the stream. It should be working correctly now but if you're running into issues, definitely let me know. I'll close this issue, but open a new one if there are indeed issues.
