### ISSUE TITLE
Feature request : Express support.

### ISSUE THREAD

**Issue by glemiere** [nodejs/http2#191]
HI!

First of all, thank you very much for working on a native implementation of the HTTP/2 protocol in NodeJS, this is really awesome.
I just attempted to replace my spdy implementation by this experimental API of NodeJS v9, doing the following : 
```
const serverApp = express().use(compression());

http2.createServer({key: privateKey, cert: certificate}, serverApp);
```

But my page doesn't seem to respond. I guess it means this API doesn't support express yet, could we just merge the express magic from `http` or `https` ?

**Comment by apapirovski** [comment]
This is now in nodejs/node so issues should be opened there. Unfortunately in this case the work is on express as they're relying on the specific http1 classes. You could follow along in their repo — there's a PR and an issue tracking the work.
