### ISSUE TITLE
How to detect if client does not support http/2 ?

### ISSUE THREAD

**Issue by budarin** [nodejs/http2#192]
I have configured server with options

```js
const options = {
    ...
    allowHTTP1: true,
}
const server = http2.createSecureServer(options);
server.on('stream', (stream, headers) => {
   ...
});
```
I need to know if the client doesnt support.

**Comment by mcollina** [comment]
You can check `req.httpVersion`: https://nodejs.org/api/http2.html#http2_request_httpversion.

**Comment by budarin** [comment]
@mcollina 
I'm sorry, but there is no req in
```js
server.on('stream', (stream, headers) => {
   ...
});
```

**Comment by apapirovski** [comment]
@budarin `allowHTTP1` only works with the compatibility mode. See https://nodejs.org/api/http2.html#http2_alpn_negotiation for an example.

**Comment by budarin** [comment]
@apapirovski 
so in case of HTTP2 can I use session like stream in core API?
As I understand in case of HTTP1 I only dont use push - the rest behaviour of app is the same for both protocols. Am I right?

**Comment by budarin** [comment]
thanks, understood.
