### ISSUE TITLE
Memory leak with h2load

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#22]
As titled, memory usage grows as more data is pushed.

**Comment by jasnell** [comment]
Which? heap usage was looking pretty good last week but there is a definite growth in rss that needs to be looked into that I haven't yet had a chance to investigate

**Comment by mcollina** [comment]
RSS I presume, htop shows memory grow steadily and never going down.

**Comment by jasnell** [comment]
Yep that's consistent with what I've seen. I suspect that it has to do with
the additional buffering not getting cleaned up properly but I haven't yet
investigated

**Comment by jasnell** [comment]
I believe this has been resolved. Closing
