### ISSUE TITLE
HTTP2 meeting

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#26]
We should have a quick call to discuss how to progress this better.

How about the 20th Dec at 5pm GMT? Does it work for everyone?

Join: https://hangouts.google.com/call/t7zou5rcnnf5begg7dqqicjbcie
Watch: https://www.youtube.com/watch?v=uQtKyX0eB2A

**Comment by mcollina** [comment]
Is this on today?

**Comment by jasnell** [comment]
Oy... unfortunately I completely forgot about this one and have a schedule conflict at 5pm GMT :-( ... would it be possible to move it to Thursday?

**Comment by mcollina** [comment]
There are no issues on my side. Can we do it a bit earlier? Maybe at 17 or
18 GMT?

I'll send you an invite.
Il giorno mar 20 dic 2016 alle 16:27 James M Snell <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
@jasnell ping, should we do this call over this week?

**Comment by jasnell** [comment]
Yes, a call would be great. What days/times would be best? Want to put together a doodle? I can pretty much make any time work this week

**Comment by mcollina** [comment]
Let's a do a doodle, as others might want to join.

**Comment by evanlucas** [comment]
yay, I would be interested in joining if y'all don't mind. Thanks!

**Comment by italoacasas** [comment]
Can you guys make sure of recording this? I'm on vacations but I still have pending the "list of tests that needs to be added"...

**Comment by mcollina** [comment]
Hey folks, here is a doodle: http://doodle.com/poll/ptudtfhtgpismfzd

**Comment by targos** [comment]
@mcollina this link is 404.

**Comment by mcollina** [comment]
@targos updated http://doodle.com/poll/ptudtfhtgpismfzd.

**Comment by mcollina** [comment]
I've closed the doodle for tomorrow, Thursday 12th at 17:00 GMT.

Should I set up the hangout and the recording?

**Comment by jasnell** [comment]
yes please!

**Comment by williamkapke** [comment]
Added to the Calendar!
https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com

PS: there are several meeting following this that plan to use the live channel- so don't go over 1hr!

**Comment by mcollina** [comment]
I've added the links to join or watch at the top.

**Comment by jasnell** [comment]
Ugh. I've had a conflict come up that means I'm only going to make the first 30 minutes of this meeting. Let's see what we can accomplish in that time and maybe look at scheduling a follow on meeting for next week

**Comment by evanlucas** [comment]
Unfortunately, I've had something come up as well. Really sorry for the late notice, but I won't be able to make it today. :[

**Comment by mcollina** [comment]
Joining link updated.

**Comment by mcollina** [comment]
Some points from the meeting:

* we lose throughput on the multiple buffering levels between the JS Streams, on the writing side.
* we still plan to ship this behind a flag in Node 8.
* we still need a client implemented. 

Actions:

* @jasnell is going to merge #31.
* next up is a rebase from master and update of ng
* @jasnell is going to focus on optimizing HTTP2Stream, and we will move the HTTP2Request and HTTP2Response objects outside of the main file.
* @mcollina will rewrite HTTP2Response to behave similarly to HTTP1, i.e. inherit from `Stream`, not `Writable`. See https://github.com/nodejs/http2/blob/master/lib/_http_outgoing.js. 

@jasnell feel free to edit at will.
