### ISSUE TITLE
Feb 2017 meeting

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#38]
How about we set up a call in the next couple of weeks to discuss how this is moving forward? There have been a lot of progress.

**Comment by jasnell** [comment]
+1 ... want to set up a doodle poll?

**Comment by mcollina** [comment]
Here it is: http://doodle.com/poll/mm9ezh8eiw44nwnr

**Comment by mcollina** [comment]
If anyone has no objection, I'd go for Monday 13th at 17:00 GMT.

**Comment by williamkapke** [comment]
Welp- the 2 people on the doodle agree... sooo I'm adding it to the calendar.

**Comment by williamkapke** [comment]
Ha! @mcollina beat me to it ;)

**Comment by williamkapke** [comment]
I just realized that the Board meeting wasn't added to the calendar- which starts at the same time. I feel confident they won't move their time ;) Any chance you can move this one?

I've noticed people seem pretty interested in this topic... so it would be really cool if ya'll could broadcast it live though.

FYI @mikeal

**Comment by mikeal** [comment]
We might actually need to push the public session to the end of this month's board meeting because of a scheduling conflict with some of the people we need in the private session. Let me get back to ya'll on this.

**Comment by mcollina** [comment]
@mikeal let us know.

**Comment by mcollina** [comment]
@mikeal what's the status of this? is the board meeting moved or not?

**Comment by mikeal** [comment]
We're doing our public session at 11am PT so it's fine.

**Comment by mcollina** [comment]
Streaming URL: http://youtu.be/uVci5Ixg46U
Join: https://hangouts.google.com/call/jz2qkh3d5rhlvm24fquow2ma7me

**Comment by mcollina** [comment]
Some notes on the outstanding PRs

- round 10 #36 will be done in the next couple of weeks, the main change is how headers are passed down during response. The goal is to avoid double-copying as much as possible.
- the compatibility mode #37 is ready to go after #36 lands.

The client is still missing, so we can't really write that many unit tests. After the current open PRs, we need to get things going with a client so we can write unit tests. Some people from Google might help and contribute.

There are two "big" tasks on the testing side: 

a. do a sweep through HTTP1 tests in node, and see the major ones that we'd need to port to HTTP2
b. add all those things that are http2 specific from the spec regarding headers and combinations of those, e.g. a 304 has no trailers.

@jasnell feel free to edit this if you have anything to add.

**Comment by sebdeckers** [comment]
@mcollina The Youtube link you just posted is titled as 13 January. I believe this is the link for the Feb meeting but it is cut off after 37s. Very curious to hear where you guys are taking this effort. 👀  https://www.youtube.com/watch?v=gaGr1ravl6w

**Comment by mcollina** [comment]
The link is correct, but the title is wrong: https://www.youtube.com/watch?v=uVci5Ixg46U. I've just updated it.

**Comment by mcollina** [comment]
Fixed by #36

**Comment by mcollina** [comment]
wrong message, but it needed to be closed anyway.
