### ISSUE TITLE
Test List

### ISSUE THREAD

**Issue by italoacasas** [nodejs/http2#42]
cc: @jasnell, @mcollina, @addaleax

I start working on the test list today, I will be updating the list while gathering more information. I'm open the issue that way everyone can give feedback about what should be in/out/priority, etc...

## Test List

- [ ] Errors conditions (James list)
- [ ] Server with connections that prematurely exists (James list)
- [ ] Basic server with configuration options set (James list)
- [ ] Server that responds with a file (pipe test) (James list)
- [ ] Basic server with simple async response (James list)
- [ ] Basic server with and without TLS. Create server instance, start listening, accept request with simple sync response (James list)
- [ ] Server client error
- [ ] Response Status code
- [ ] HTTP Methods
- [ ] Invalid (URLs and headers fields)
- [ ] uncaughtException
- [ ] Default values (port, encoding, method, headers)
- [ ] Connect (request, response, length)
- [ ] DNS error

### Client

- [ ] abort event
- [ ] abort
- [ ] aborted event
- [ ] agent
- [ ] check HTTP token
- [ ] default headers exist
- [ ] default
- [ ] encoding
- [ ] get URL
- [ ] keep alive release before the finish
- [ ] parse error
- [ ] pipe end
- [ ] read in error
- [ ] readable
- [ ] reject chunked with content length
- [ ] response domain

**Comment by mcollina** [comment]
hey @italoacasas, since today we have a minimal http2 client (see #43). The API is definitely not finalized, but we can definitely get some help in ramping up the test and test coverage. Maybe we can turn that bullet list into a task lists, and start adding those.
I think those tests would help in driving the client API.

cc @jasnell

**Comment by italoacasas** [comment]
@mcollina I'm not going to be around next week.

-  I change the list for bullets point.

- The list is a work in progress, still pending most of the server tests. But at least we have a guide for a portion of what we need to do. I will work on this if no-one does when I come back.

- Maybe creating a Project is a good idea, remember the way we did this for the `streams internal states` tests?

**Comment by mcollina** [comment]
@italoacasas definitely. We can do a project, and open some issues here.
It's a ton of work, as I expect those features *not* to work as expected (vs what we did for streams).
