### ISSUE TITLE
delayed open scenario

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#44]
I'm trying to add "delayed open" scenario, and I am trying to create an `Http2Stream` before we have a connected socket. 

I have a prototype that defers  `handle.consume(socket._handle._externalStream);`, but then I get into:

```
    frame #0: 0x00000001009ab8b0 node`node::http2::Http2Session::Send(this=0x0000000103803400, buf=0x00000001023292d0, length=58) + 38 at node_http2.cc:697 [opt]
   694  void Http2Session::Send(uv_buf_t* buf,
   695                          size_t length) {
   696    // Do not attempt to write data if the stream is not alive or is closing
-> 697    if (stream_ == nullptr || !stream_->IsAlive() || stream_->IsClosing()) {
   698      return;
   699    }
   700
```

@jasnell do you think what I am trying to achieve is feasible?

**Comment by jasnell** [comment]
hmm... it's feasible but not with the code written the way it is now. The underlying nghttp_session is not created until the Http2Session object is created and that object requires the socket external to be passed. We can separate the construction of those two by having a separate method for attaching the socket external.

**Comment by jasnell** [comment]
Closing this as we having a working solution for now. It can be improved, however.
