### ISSUE TITLE
Cannot find res.createPushResponse() in Http2Response.

### ISSUE THREAD

**Issue by mahdi-shojaee** [nodejs/http2#46]
* **v8.0.0-pre**:
* **Darwin**:

Thanks for your nice work.

Seems that the [doc](https://github.com/nodejs/http2/blob/master/doc/http2-implementation-notes.md#method-responsecreatepushresponse) for the `http2` is not updated, I know that the `http2` module itself implemented as a separate module named `http2` but cannot find the `res.createPushResponse` method. Can you please help me?

Thanks again.

**Comment by mcollina** [comment]
This is a work in progress branch, and things might slip out of sync.
Would you like to help by contributing to this one?

**Comment by mahdi-shojaee** [comment]
I like to help by any contribution, but unfortunately these days I'm so busy.
