### ISSUE TITLE
Client hangs after first WINDOW_UPDATE

### ISSUE THREAD

**Issue by kjin** [nodejs/http2#55]
The client seems to hang sometimes after sending its first `WINDOW_UPDATE` frame, and this is most readily seen when it opens a single stream with a small `initialWindowSize`. In C++, `DrainCallbacks` isn't being called after the first window update frame is sent.

I think there is a race condition involved, given that opening multiple streams increases the likelihood that all streams will receive all of their data without hanging, probably because the interleaving gives each stream enough time to reset state or something.

Maybe this is related to #19?

**Comment by jasnell** [comment]
@kjin ... is this resolved now?

**Comment by jasnell** [comment]
I believe this is resolved now. @kjin, if not, I'll reopen
