### ISSUE TITLE
Http2Session::destroy doesn't destroy associated socket

### ISSUE THREAD

**Issue by kjin** [nodejs/http2#62]
`Http2Session::destroy` doesn't call destroy on its socket, so in order to close a connection completely on the client side, `socket.destroy()` must be called on the socket exposed by the `Http2Session` object.

I noticed that `socket.destroy` calls `destroy` on its parent session (I would've expected the other way around). Is there a reason for doing this?

**Comment by jasnell** [comment]
this should be fixed now
