### ISSUE TITLE
HTTP/2 requests

### ISSUE THREAD

**Issue by unbalanced** [nodejs/http2#63]
Hey guys, i see this is a WIP repo - way to go for that important feature!

My question:
Is it part of the plan to add support for HTTP/2 for requests going out of a node app (client mode) 
e.g. something like
```
http.request(options[, callback])
```
Will use HTTP/2.

(asking since all the discussions that i've seen here are referring to adding HTTP/2 server capabilities)

Many thanks.

**Comment by mcollina** [comment]
the model for http2 will be slightly different, you'll have to do http2.connect() to create a session, and then you could issue your requests. Feel free to check the tests, some of them use the client.

**Comment by unbalanced** [comment]
@mcollina - Thanks for the fast response.
