### ISSUE TITLE
http2: websocket upgrade path?

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#68]
How this is supported in HTTP2?

**Comment by lpinca** [comment]
AFAIK there is no spec: https://daniel.haxx.se/blog/2016/06/15/no-websockets-over-http2/

**Comment by mcollina** [comment]
OOh, so in our compat layer and upgrade path, we should check that it still working perfectly with WebSocket.

**Comment by jasnell** [comment]
for http/1 yes, when using http/2, the `Upgrade` header is illegal to use so there actually is not a method for upgrading to WebSockets when using http/2. We'll need to make sure that the upgrade to WebSockets from HTTP/1 still works once we've added the support for upgrading to http/2 but the rest is still entirely up in the air. We'll have to document that there's no way to use http/2 and websockets together.
