### ISSUE TITLE
Process notes

### ISSUE THREAD

**Issue by jasnell** [nodejs/http2#79]
Now that we have quite a few more people looking at this and looking to contribute, we should start formalizing the process. I talked about some of this at the collaborator summit meeting yesterday, so I apologize if it's a repeat for some of you.

1. Up to this point, it's largely been @mcollina and I working on this so we hadn't been following a more formal review and sign off process. Now that there are more of us, we'll do the sign off on PRs like we do in core. We may not need to wait the full 48 hours to land stuff, but we still will need sign off before landing things.

2. Force pushes to master *will* happen. I will only do these when either (a) rebasing nodejs/http2 master with nodejs/node master to keep things up to date or (b) squashing commits to clean up the history (see item 3 below).

3. For the most part, we're going to start maintaining separate commits rather than squashing those down like we have been. This will ensure a proper history to be maintained, which will be important once we get around to opening the PR to nodejs/master. That said, there are no doubt going to be smaller commits that can be squashed (usually small trivial type fixes). If you're ok with your commits being squashed into the history. Put `(Squash)` in some way in the commit message and I'll use that as a guide.

4. We have the nodejs/http2 team that will have commit rights to this repo. If you'd like to join that team, let either myself or @mcollina know and we'll get you added.

5. A number of tracking issues with the outstanding todos have been opened following the discussion at collab summit yesterday. These do not yet have a lot of detail in them and I will be working to fill out that detail. These will be he ideal areas of jumping in to help. If you'd like to work on a particular area, please drop a comment into the thread so that others know what you're working on in order to avoid accidentally duplicating work.

6. I will be scheduling a weekly status hangout to discuss ongoing progress. I have no idea what times will work yet. Expect a doodle poll to be posted.

**Comment by igwejk** [comment]
@jasnell I'd like to contribute too. Do you have any pointers to share on how to get in and get started?

/cc @mcollina

**Comment by mcollina** [comment]
@igwejk I think you should read https://github.com/nodejs/http2/blob/master/doc/http2-implementation-notes.md and go through our current tests.

Increasing the code coverage would be handy, but also porting tests that have been written for HTTP1. Also start documenting things might be useful https://github.com/nodejs/http2/issues/98.
