### ISSUE TITLE
HTTP2 docs

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#98]
We should start working on docs, as it would be easier to onboard new collabs.
Also, docs would show inconsistencies in the API, so it's a good idea overall.

**Comment by jasnell** [comment]
Yep, a docs PR should be opened by Friday

**Comment by jasnell** [comment]
See: https://github.com/nodejs/http2/pull/102

**Comment by jasnell** [comment]
Docs in and landed. Need additional ongoing work but will close this issue.
